### ISSUE TITLE
Global link colour overriden when including sass

### ISSUE THREAD

**Issue by timcowlishaw** [nationalarchives/tna-frontend#97]
Hi there folks!

I don't fully get what's going on here, but i had a weird issue when including tna-frontend in nationalarchives/ds-caselaw-public-ui in that the tna-frontend css globally overrode our link style with an undefined variable, leading to all links showing as black:

<img width="1177" alt="image" src="https://github.com/nationalarchives/tna-frontend/assets/4279/297961e8-f19e-4e04-b5bd-aafe63e6e33f">

(note that the titles of judgments are black, as are the unselected pagination links, rendering them effectively invisible).

I haven't been able to track down exactly where in tna-frontend that `color: var(--link)` directive comes from - bizarrely it also seems to take precedence over other more specific rules in our own codebase - even if i set `--link` to our global link colour *before* including the tna-frontend css, it still seems to take precedence over other more specific selectors in our own css? I've managed to get around this by sprinkling some `!important`s around our codebase, but would be good to understand a bit better what's actually going on.

thank you!

Tim

**Comment by ahosgood** [comment]
The colour of the links is set by the selected [theme](https://nationalarchives.github.io/design-system/styles/colours/#theme-colours).

You will need a `tna-template` class in the `<html>` element as well as either:

- `tna-template--system-theme` or
- `tna-template--light-theme` or
- `tna-template--dark-theme`

This will then set all the CSS custom properties we need for colours:

<img width="1280" alt="image" src="https://github.com/nationalarchives/tna-frontend/assets/2356642/50354066-0d97-4cbf-a946-a643113d6142">

Without these classes, I imagine the links will default to black because there is no variable set.

**Comment by ahosgood** [comment]
The resets for images, videos, canvases etc. are only element specificity (0-0-1) which means they can be overwritten with a single class (0-1-0). If we were to scope them inside another class (e.g. `.tna-template img` 0-1-1) then overwriting those styles for an image within a component using BEM (e.g. `.tna-card__image` 0-1-0) wouldn't be possible without more specific selectors.

The same applies to the `*` selector - scoping that makes it more important and then harder to override. There are also quite a number of elements that benefit from the `margin: 0; padding: 0;` reset and I don't think we could remove that without quite a bit of work and testing.

The main consumers of TNA Frontend will be creating new services using the library rather than migrating existing ones. Given that there are so many different possible styles and libraries that other services could be using I think we could potentially spend too long trying to make it more seamless for a number of one-time migrations when instead we could be improving and adding to the components we have. We also have to be aware that we are a very small and focused team.

I need to have a think about this and what the best way forward is.
